name: example
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.7
  dio: ^5.4.0
  fpdart: ^1.1.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  retrofit_wrapper:
    git:
      url: https://github.com/ebwood/retrofit_wrapper_tools
      path: retrofit_wrapper
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  retrofit_wrapper_generator:
    git:
      url: https://github.com/ebwood/retrofit_wrapper_tools
      path: retrofit_wrapper_generator
